import BackgroundGeolocation, {
  State,
  Config,
  Location,
  LocationError,
  Geofence,
  HttpEvent,
  MotionActivityEvent,
  ProviderChangeEvent,
  MotionChangeEvent,
  GeofenceEvent,
  GeofencesChangeEvent,
  HeartbeatEvent,
  ConnectivityChangeEvent,
  DeviceSettings,
  DeviceSettingsRequest,
  Notification,
  DeviceInfo,
  Authorization,
  AuthorizationEvent,
  TransistorAuthorizationToken,
  Subscription,
} from 'react-native-background-geolocation';
import {GeofenceAction} from './types';

export default BackgroundGeolocation;

export type {
  State,
  Config,
  Location,
  LocationError,
  Geofence,
  HttpEvent,
  MotionActivityEvent,
  ProviderChangeEvent,
  MotionChangeEvent,
  GeofenceEvent,
  GeofencesChangeEvent,
  HeartbeatEvent,
  ConnectivityChangeEvent,
  DeviceSettings,
  DeviceSettingsRequest,
  Notification,
  DeviceInfo,
  Authorization,
  AuthorizationEvent,
  TransistorAuthorizationToken,
  Subscription,
  GeofenceAction,
};
